package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name = "absence", schema = "public")
public class Absence implements java.io.Serializable {

	private int idabsence;
	private Eleve eleve;
	private Date date;
	private Date heured;
	private Date heuref;
	private String justificatiion;

	public Absence() {
	}

	public Absence(int idabsence) {
		this.idabsence = idabsence;
	}

	public Absence(int idabsence, Eleve eleve, Date date, Date heured, Date heuref, String justificatiion) {
		this.idabsence = idabsence;
		this.eleve = eleve;
		this.date = date;
		this.heured = heured;
		this.heuref = heuref;
		this.justificatiion = justificatiion;
	}

	@Id

	@Column(name = "idabsence", unique = true, nullable = false)
	@GeneratedValue
	public int getIdabsence() {
		return this.idabsence;
	}

	public void setIdabsence(int idabsence) {
		this.idabsence = idabsence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eleve")
	public Eleve getEleve() {
		return this.eleve;
	}

	public void setEleve(Eleve eleve) {
		this.eleve = eleve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "heured")
	public Date getHeured() {
		return this.heured;
	}

	public void setHeured(Date heured) {
		this.heured = heured;
	}

	@Column(name = "heuref")
	public Date getHeuref() {
		return this.heuref;
	}

	public void setHeuref(Date heuref) {
		this.heuref = heuref;
	}

	@Column(name = "justificatiion", length = 254)
	public String getJustificatiion() {
		return this.justificatiion;
	}

	public void setJustificatiion(String justificatiion) {
		this.justificatiion = justificatiion;
	}

}
