package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActiviteExtra generated by hbm2java
 */
@Entity
@Table(name = "activite_extra", schema = "public")
public class ActiviteExtra implements java.io.Serializable {

	private int idActivite;
	private Date dateActivite;
	private Date heured;
	private Date heuref;
	private String nom;
	private String lieux;
	private String description;
	private int frais;
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public ActiviteExtra() {
	}

	public ActiviteExtra(int idActivite) {
		this.idActivite = idActivite;
	}

	public ActiviteExtra(int idActivite, Date dateActivite, Date heured, Date heuref, String nom,
			Set<Eleve> eleves) {
		this.idActivite = idActivite;
		this.dateActivite = dateActivite;
		this.heured = heured;
		this.heuref = heuref;
		this.nom = nom;
		this.eleves = eleves;
	}

	@Id

	@Column(name = "id_activite", unique = true, nullable = false)
	@GeneratedValue
	public int getIdActivite() {
		return this.idActivite;
	}

	public void setIdActivite(int idActivite) {
		this.idActivite = idActivite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_activite", length = 13)
	public Date getDateActivite() {
		return this.dateActivite;
	}

	public void setDateActivite(Date dateActivite) {
		this.dateActivite = dateActivite;
	}

	 @Temporal(TemporalType.TIMESTAMP)
	 @Column(name = "heured", length = 29)
	public Date getHeured() {
		return this.heured;
	}

	public void setHeured(Date heured) {
		this.heured = heured;
	}

	 @Temporal(TemporalType.TIMESTAMP)
	 @Column(name = "heuref", length = 29)
	
	public Date getHeuref() {
		return this.heuref;
	}

	public void setHeuref(Date heuref) {
		this.heuref = heuref;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "activiteExtras")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}
	
	
	@Column(name = "description", length = 254)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "lieux", length = 254)
	public String getLieux() {
		return lieux;
	}

	public void setLieux(String lieux) {
		this.lieux = lieux;
	}

	@Column(name = "frais")
	public int getFrais() {
		return frais;
	}

	public void setFrais(int frais) {
		this.frais = frais;
	}

}
