package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", schema = "public")
public class Administrateur implements java.io.Serializable {

	private int idadministrateur;
	private Personne personne;
	private Integer codepermisson;
	private String role;

	public Administrateur() {
	}

	public Administrateur(int idadministrateur) {
		this.idadministrateur = idadministrateur;
	}

	public Administrateur(int idadministrateur, Personne personne, Integer codepermisson, String role) {
		this.idadministrateur = idadministrateur;
		this.personne = personne;
		this.codepermisson = codepermisson;
		this.role = role;
	}

	@Id

	@Column(name = "idadministrateur", unique = true, nullable = false, length = 254)
	@GeneratedValue
	public int getIdadministrateur() {
		return this.idadministrateur;
	}

	public void setIdadministrateur(int idadministrateur) {
		this.idadministrateur = idadministrateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personne")
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "codepermisson")
	public Integer getCodepermisson() {
		return this.codepermisson;
	}

	public void setCodepermisson(Integer codepermisson) {
		this.codepermisson = codepermisson;
	}

	@Column(name = "role", length = 254)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
