package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssoEleveEvaluationId generated by hbm2java
 */
@Embeddable
public class AssoEleveEvaluationId implements java.io.Serializable {

	private int idEleve;
	private int idEvaluation;

	public AssoEleveEvaluationId() {
	}

	public AssoEleveEvaluationId(int idEleve, int idEvaluation) {
		this.idEleve = idEleve;
		this.idEvaluation = idEvaluation;
	}

	@Column(name = "id_eleve", nullable = false)
	public int getIdEleve() {
		return this.idEleve;
	}

	public void setIdEleve(int idEleve) {
		this.idEleve = idEleve;
	}

	@Column(name = "id_evaluation", nullable = false)
	public int getIdEvaluation() {
		return this.idEvaluation;
	}

	public void setIdEvaluation(int idEvaluation) {
		this.idEvaluation = idEvaluation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssoEleveEvaluationId))
			return false;
		AssoEleveEvaluationId castOther = (AssoEleveEvaluationId) other;

		return (this.getIdEleve() == castOther.getIdEleve()) && (this.getIdEvaluation() == castOther.getIdEvaluation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEleve();
		result = 37 * result + this.getIdEvaluation();
		return result;
	}

}
