package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssoClasseCoursId generated by hbm2java
 */
@Embeddable
public class AssoClasseCoursId implements java.io.Serializable {

	private int idCours;
	private int idclasse;

	public AssoClasseCoursId() {
	}

	public AssoClasseCoursId(int idCours, int idclasse) {
		this.idCours = idCours;
		this.idclasse = idclasse;
	}

	@Column(name = "id_cours", nullable = false)
	public int getIdCours() {
		return this.idCours;
	}

	public void setIdCours(int idCours) {
		this.idCours = idCours;
	}

	@Column(name = "idclasse", nullable = false)
	public int getIdclasse() {
		return this.idclasse;
	}

	public void setIdclasse(int idclasse) {
		this.idclasse = idclasse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssoClasseCoursId))
			return false;
		AssoClasseCoursId castOther = (AssoClasseCoursId) other;

		return (this.getIdCours() == castOther.getIdCours()) && (this.getIdclasse() == castOther.getIdclasse());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCours();
		result = 37 * result + this.getIdclasse();
		return result;
	}

}
