package entitee;

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Column;

/**
 * AssoClasseCours generated by hbm2java
 */
@Entity
@Table(name = "asso_classe_cours", schema = "public")
public class AssoClasseCours implements java.io.Serializable {

    private int id; 
    private Classes classes;
    private Cours cours;
    private Professeur professeur; // Relation ManyToOne
    private Date date;
    private Date heured;
    private Date heuref;

    public AssoClasseCours() {
    }

    public AssoClasseCours(int id, Classes classes, Cours cours, Professeur professeur) {
        this.id = id;
        this.classes = classes;
        this.cours = cours;
        this.professeur = professeur;
    }

    public AssoClasseCours(int id, Classes classes, Cours cours, Professeur professeur, Date date, Date heured, Date heuref) {
        this.id = id;
        this.classes = classes;
        this.cours = cours;
        this.professeur = professeur;
        this.date = date;
        this.heured = heured;
        this.heuref = heuref;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "id_classe", nullable = false)
    public Classes getClasses() {
        return this.classes;
    }

    public void setClasses(Classes classes) {
        this.classes = classes;
    }

    @ManyToOne
    @JoinColumn(name = "id_cours", nullable = false)
    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    @ManyToOne
    @JoinColumn(name = "id_professeur", nullable = false) // Relation avec Professeur
    public Professeur getProfesseur() {
        return this.professeur;
    }

    public void setProfesseur(Professeur professeur) {
        this.professeur = professeur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", length = 13)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "heured", length = 29)
    public Date getHeured() {
        return this.heured;
    }

    public void setHeured(Date heured) {
        this.heured = heured;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "heuref", length = 29)
    public Date getHeuref() {
        return this.heuref;
    }

    public void setHeuref(Date heuref) {
        this.heuref = heuref;
    }
    public Classes getClasse() {
        return this.classes;
    }
    
    public void setClasse(Classes classe) {
        this.classes = classe;
    }

}
