package entitee;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Column;

/**
 * AssoEleveEvaluation generated by hbm2java
 */
@Entity
@Table(name = "asso_eleve_evaluation", schema = "public")
public class AssoEleveEvaluation implements java.io.Serializable {

    private int id; // Identifiant unique
    private Eleve eleve;
    private Evaluation evaluation;
    private Float note;

    public AssoEleveEvaluation() {
    }

    public AssoEleveEvaluation(int id, Eleve eleve, Evaluation evaluation) {
        this.id = id;
        this.eleve = eleve;
        this.evaluation = evaluation;
    }

    public AssoEleveEvaluation(int id, Eleve eleve, Evaluation evaluation, Float note) {
        this.id = id;
        this.eleve = eleve;
        this.evaluation = evaluation;
        this.note = note;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "id_eleve", nullable = false)
    public Eleve getEleve() {
        return this.eleve;
    }

    public void setEleve(Eleve eleve) {
        this.eleve = eleve;
    }

    @ManyToOne
    @JoinColumn(name = "id_evaluation", nullable = false)
    public Evaluation getEvaluation() {
        return this.evaluation;
    }

    public void setEvaluation(Evaluation evaluation) {
        this.evaluation = evaluation;
    }

    @Column(name = "note", precision = 8, scale = 8)
    public Float getNote() {
        return this.note;
    }

    public void setNote(Float note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AssoEleveEvaluation that = (AssoEleveEvaluation) o;

        return id == that.id;
    }

    @Override
    public int hashCode() {
        return id;
    }
}
