package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BatimentAdministratif generated by hbm2java
 */
@Entity
@Table(name = "batiment_administratif", schema = "public")
public class BatimentAdministratif implements java.io.Serializable {

	private String idBat;
	private Ecole ecole;
	private Integer nbreSalles;
	private String nom;

	public BatimentAdministratif() {
	}

	public BatimentAdministratif(String idBat) {
		this.idBat = idBat;
	}

	public BatimentAdministratif(String idBat, Ecole ecole, Integer nbreSalles, String nom) {
		this.idBat = idBat;
		this.ecole = ecole;
		this.nbreSalles = nbreSalles;
		this.nom = nom;
	}

	@Id

	@Column(name = "id_bat", unique = true, nullable = false, length = 10)
	@GeneratedValue
	public String getIdBat() {
		return this.idBat;
	}

	public void setIdBat(String idBat) {
		this.idBat = idBat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ecole")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "nbre_salles")
	public Integer getNbreSalles() {
		return this.nbreSalles;
	}

	public void setNbreSalles(Integer nbreSalles) {
		this.nbreSalles = nbreSalles;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
