package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cantine generated by hbm2java
 */
@Entity
@Table(name = "cantine", schema = "public")
public class Cantine implements java.io.Serializable {

	private int idCantine;
	private Ecole ecole;
	private String menu;
	private Integer prix;
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Cantine() {
	}

	public Cantine(int idCantine) {
		this.idCantine = idCantine;
	}

	public Cantine(int idCantine, Ecole ecole, String menu, Integer prix, Set<Eleve> eleves) {
		this.idCantine = idCantine;
		this.ecole = ecole;
		this.menu = menu;
		this.prix = prix;
		this.eleves = eleves;
	}

	@Id

	@Column(name = "id_cantine", unique = true, nullable = false)
	@GeneratedValue
	public int getIdCantine() {
		return this.idCantine;
	}

	public void setIdCantine(int idCantine) {
		this.idCantine = idCantine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ecole")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "menu", length = 254)
	public String getMenu() {
		return this.menu;
	}

	public void setMenu(String menu) {
		this.menu = menu;
	}

	@Column(name = "prix")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cantine")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

}
