package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name = "cours", schema = "public")
public class Cours implements java.io.Serializable {

	private int idCours;
	private String description;
	private String matiere;
	private Set<AssoClasseCours> assoClasseCourses = new HashSet<AssoClasseCours>(0);
	private Set<Professeur> professeurs = new HashSet<Professeur>(0);
	private Set<Salle> salles = new HashSet<Salle>(0);
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);

	public Cours() {
	}

	public Cours(int idCours) {
		this.idCours = idCours;
	}

	public Cours(int idCours, String description, String matiere, Set<AssoClasseCours> assoClasseCourses,
			Set<Professeur> professeurs, Set<Salle> salles, Set<Evaluation> evaluations) {
		this.idCours = idCours;
		this.description = description;
		this.matiere = matiere;
		this.assoClasseCourses = assoClasseCourses;
		this.professeurs = professeurs;
		this.salles = salles;
		this.evaluations = evaluations;
	}

	@Id

	@Column(name = "id_cours", unique = true, nullable = false)
	@GeneratedValue
	public int getIdCours() {
		return this.idCours;
	}

	public void setIdCours(int idCours) {
		this.idCours = idCours;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "matiere", length = 254)
	public String getMatiere() {
		return this.matiere;
	}

	public void setMatiere(String matiere) {
		this.matiere = matiere;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
	public Set<AssoClasseCours> getAssoClasseCourses() {
		return this.assoClasseCourses;
	}

	public void setAssoClasseCourses(Set<AssoClasseCours> assoClasseCourses) {
		this.assoClasseCourses = assoClasseCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
	public Set<Professeur> getProfesseurs() {
		return this.professeurs;
	}

	public void setProfesseurs(Set<Professeur> professeurs) {
		this.professeurs = professeurs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "courses")
	public Set<Salle> getSalles() {
		return this.salles;
	}

	public void setSalles(Set<Salle> salles) {
		this.salles = salles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
	public Set<Evaluation> getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}

}
