package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecole generated by hbm2java
 */
@Entity
@Table(name = "ecole", schema = "public")
public class Ecole implements java.io.Serializable {

	private int idEcole;
	private String nom;
	private Set<Salle> salles = new HashSet<Salle>(0);
	private Set<BusTransport> busTransports = new HashSet<BusTransport>(0);
	private Set<Infirmerie> infirmeries = new HashSet<Infirmerie>(0);
	private Set<Cantine> cantines = new HashSet<Cantine>(0);
	private Set<Professeur> professeurs = new HashSet<Professeur>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);
	private Set<BatimentAdministratif> batimentAdministratifs = new HashSet<BatimentAdministratif>(0);

	public Ecole() {
	}

	public Ecole(int idEcole) {
		this.idEcole = idEcole;
	}

	public Ecole(int idEcole, String nom, Set<Salle> salles, Set<BusTransport> busTransports,
			Set<Infirmerie> infirmeries, Set<Cantine> cantines, Set<Professeur> professeurs, Set<Eleve> eleves,
			Set<BatimentAdministratif> batimentAdministratifs) {
		this.idEcole = idEcole;
		this.nom = nom;
		this.salles = salles;
		this.busTransports = busTransports;
		this.infirmeries = infirmeries;
		this.cantines = cantines;
		this.professeurs = professeurs;
		this.eleves = eleves;
		this.batimentAdministratifs = batimentAdministratifs;
	}

	@Id

	@Column(name = "id_ecole", unique = true, nullable = false)
	@GeneratedValue
	public int getIdEcole() {
		return this.idEcole;
	}

	public void setIdEcole(int idEcole) {
		this.idEcole = idEcole;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Salle> getSalles() {
		return this.salles;
	}

	public void setSalles(Set<Salle> salles) {
		this.salles = salles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<BusTransport> getBusTransports() {
		return this.busTransports;
	}

	public void setBusTransports(Set<BusTransport> busTransports) {
		this.busTransports = busTransports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Infirmerie> getInfirmeries() {
		return this.infirmeries;
	}

	public void setInfirmeries(Set<Infirmerie> infirmeries) {
		this.infirmeries = infirmeries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Cantine> getCantines() {
		return this.cantines;
	}

	public void setCantines(Set<Cantine> cantines) {
		this.cantines = cantines;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ecoles")
	public Set<Professeur> getProfesseurs() {
		return this.professeurs;
	}

	public void setProfesseurs(Set<Professeur> professeurs) {
		this.professeurs = professeurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<BatimentAdministratif> getBatimentAdministratifs() {
		return this.batimentAdministratifs;
	}

	public void setBatimentAdministratifs(Set<BatimentAdministratif> batimentAdministratifs) {
		this.batimentAdministratifs = batimentAdministratifs;
	}

}
