package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Infirmerie generated by hbm2java
 */
@Entity
@Table(name = "infirmerie", schema = "public")
public class Infirmerie implements java.io.Serializable {

	private int idinfirmerie;
	private Ecole ecole;
	private Date dateVisite;
    private String medicamentsAdministres;
	private String diagnostic;
	private String motifvisite;
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Infirmerie() {
	}

	public Infirmerie(int idinfirmerie) {
		this.idinfirmerie = idinfirmerie;
	}

	public Infirmerie(int idinfirmerie, Ecole ecole, Date dateVisite, String diagnostic, String motifvisite,
			Set<Eleve> eleves) {
		this.idinfirmerie = idinfirmerie;
		this.ecole = ecole;
		this.dateVisite = dateVisite;
		this.diagnostic = diagnostic;
		this.motifvisite = motifvisite;
		this.eleves = eleves;
	}

	@Id

	@Column(name = "idinfirmerie", unique = true, nullable = false)
	@GeneratedValue
	public int getIdinfirmerie() {
		return this.idinfirmerie;
	}

	public void setIdinfirmerie(int idinfirmerie) {
		this.idinfirmerie = idinfirmerie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ecole")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_visite", length = 13)
	public Date getDateVisite() {
		return this.dateVisite;
	}

	public void setDateVisite(Date dateVisite) {
		this.dateVisite = dateVisite;
	}

	@Column(name = "diagnostic", length = 254)
	public String getDiagnostic() {
		return this.diagnostic;
	}

	public void setDiagnostic(String diagnostic) {
		this.diagnostic = diagnostic;
	}

	@Column(name = "motifvisite", length = 254)
	public String getMotifvisite() {
		return this.motifvisite;
	}

	public void setMotifvisite(String motifvisite) {
		this.motifvisite = motifvisite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infirmerie")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}
	
	
	@Column(name = "medicamentAdminis", length = 254)
	public String getMedicamentsAdministres() {
		return medicamentsAdministres;
	}

	public void setMedicamentsAdministres(String medicamentsAdministres) {
		this.medicamentsAdministres = medicamentsAdministres;
	}

}
