package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name = "paiement", schema = "public")
public class Paiement implements java.io.Serializable {

	private int idPaiement;
	private Eleve eleve;
	private Date datePaiement;
	private String statutPaiement;
	
	private Integer montant;
	private String mois;
	private String typePaiement;

	public Paiement() {
	}

	public Paiement(int idPaiement) {
		this.idPaiement = idPaiement;
	}

	public Paiement(int idPaiement, Eleve eleve, Date datePaiement, Integer montant, String typePaiement) {
		this.idPaiement = idPaiement;
		this.eleve = eleve;
		this.datePaiement = datePaiement;
		this.montant = montant;
		this.typePaiement = typePaiement;
	}

	@Id

	@Column(name = "id_paiement", unique = true, nullable = false)
	@GeneratedValue
	public int getIdPaiement() {
		return this.idPaiement;
	}

	public void setIdPaiement(int idPaiement) {
		this.idPaiement = idPaiement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eleve")
	public Eleve getEleve() {
		return this.eleve;
	}

	public void setEleve(Eleve eleve) {
		this.eleve = eleve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_paiement", length = 13)
	public Date getDatePaiement() {
		return this.datePaiement;
	}

	public void setDatePaiement(Date datePaiement) {
		this.datePaiement = datePaiement;
	}

	@Column(name = "montant")
	public Integer getMontant() {
		return this.montant;
	}

	public void setMontant(Integer montant) {
		this.montant = montant;
	}

	@Column(name = "type_paiement", length = 254)
	public String getTypePaiement() {
		return this.typePaiement;
	}

	public void setTypePaiement(String typePaiement) {
		this.typePaiement = typePaiement;
	}
	@Column(name = "statut_paiement", length = 50)
	public String getStatutPaiement() {
		return statutPaiement;
	}

	public void setStatutPaiement(String statutPaiement) {
		this.statutPaiement = statutPaiement;
	}
	
	@Column(name = "mois", length = 50)
	public String getMois() {
		return mois;
	}

	public void setMois(String mois) {
		this.mois = mois;
	}

}
