package entitee;
// Generated 3 sept. 2024, 20:23:09 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salle generated by hbm2java
 */
@Entity
@Table(name = "salle", schema = "public")
public class Salle implements java.io.Serializable {

	private int idSalle;
	private Ecole ecole;
	private Integer capacite;
	private String nom;
	private Set<Cours> courses = new HashSet<Cours>(0);

	public Salle() {
	}

	public Salle(int idSalle) {
		this.idSalle = idSalle;
	}

	public Salle(int idSalle, Ecole ecole, Integer capacite, String nom, Set<Cours> courses) {
		this.idSalle = idSalle;
		this.ecole = ecole;
		this.capacite = capacite;
		this.nom = nom;
		this.courses = courses;
	}

	@Id

	@Column(name = "id_salle", unique = true, nullable = false)
	@GeneratedValue
	public int getIdSalle() {
		return this.idSalle;
	}

	public void setIdSalle(int idSalle) {
		this.idSalle = idSalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ecole")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@Column(name = "capacite")
	public Integer getCapacite() {
		return this.capacite;
	}

	public void setCapacite(Integer capacite) {
		this.capacite = capacite;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "asso_cours_salle", schema = "public", joinColumns = {
			@JoinColumn(name = "id_salle", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_cours", nullable = false, updatable = false) })
	public Set<Cours> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Cours> courses) {
		this.courses = courses;
	}

}
