package entitee;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.Set;

/**
 * Tuteur generated by hbm2java
 */
@Entity
@Table(name = "tuteur", schema = "public")
public class Tuteur implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id_tuteur", unique = true, nullable = false)
    private int idTuteur;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_personne", nullable = false)
    private Personne personne; // Clé étrangère vers la table personne
    
    @Column(name = "relation", length = 254)
    private String relation;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tuteur")
    private Set<Eleve> eleves; // Liste des élèves sous la responsabilité de ce tuteur

    // Constructeurs, getters, et setters

    public Tuteur() {
    }

    public Tuteur(int idtuteur, Personne personne) {
        this.idTuteur = idtuteur;
        this.personne = personne;
    }

    public Tuteur(int idtuteur, Personne personne, String relation) {
        this.idTuteur = idtuteur;
        this.personne = personne;
        this.relation = relation;
    }

    public int getIdTuteur() {
        return this.idTuteur;
    }

    public void setIdTuteur(int idTuteur) {
        this.idTuteur = idTuteur;
    }

    public Personne getPersonne() {
        return this.personne;
    }

    public void setPersonne(Personne personne) {
        this.personne = personne;
    }

    public String getRelation() {
        return this.relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public Set<Eleve> getEleves() {
        return this.eleves;
    }

    public void setEleves(Set<Eleve> eleves) {
        this.eleves = eleves;
    }
}
